wandb_version: 1

init_filters:
  desc: null
  value: 16
dropout_prob:
  desc: null
  value: 0.2
max_epochs:
  desc: null
  value: 100
lrate:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 1.0e-05
batch_size:
  desc: null
  value: 1
threshold:
  desc: null
  value: 0.5
use_scaler:
  desc: null
  value: true
use_autocast:
  desc: null
  value: true
GT:
  desc: null
  value: nroi + froi
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714955638.254238
    t:
      1:
      - 1
      - 48
      - 55
      2:
      - 1
      - 48
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.15.10
      8:
      - 5
